### ISSUE TITLE
Support for Kerberos password authentication

### ISSUE THREAD

**Issue by nilesh-unifi** [tkdchen/python-krbcontext#14]
Hi,

Is it possible to add support for Kerberos password authentication without prompting for password? 

IMO, this should be possible by adding following in init_ccache_as_regular_user method and allowing an option for password to be passed in krbcontext()

```
kinit_proc = subprocess.Popen(cmd_to_execute, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
if password:
    kinit_proc.stdin.write('%s\n' % password)
else:
     stdout_data, stderr_data = kinit_proc.communicate()
    __init_lock.release()
```

Regards,

**Comment by tkdchen** [comment]
Related to #15

**Comment by tkdchen** [comment]
Depends on #20

**Comment by tkdchen** [comment]
This is fixed by using ``python-gssapi``. Password can be passed to krbcontext via a parameter. ``kinit`` is no longer a dependency.
