### ISSUE TITLE
I am getting ImportError in krbcontext/__init__.py

### ISSUE THREAD

**Issue by rajesh-erasani** [tkdchen/python-krbcontext#18]
$ python

import krbcontext

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<home>/python3.5/site-packages/krbcontext/**init**.py", line 3, in <module>
    from context import *
ImportError: No module named 'context'

**Comment by tkdchen** [comment]
Sorry, krbcontext currently does not support Python 3.

**Comment by tkdchen** [comment]
Depends on #12

**Comment by tkdchen** [comment]
Latest version of ``0.6`` is compatible with Python 3.
