### ISSUE TITLE
Replace python-krbV with python-gssapi

### ISSUE THREAD

**Issue by tkdchen** [tkdchen/python-krbcontext#20]
https://github.com/pythongssapi/python-gssapi

**Comment by fbacchella** [comment]
Any progress ? In the documentation, the link to https://fedorahosted.org/python-krbV/ is dead, pip install krbV returns Could not find any downloads that satisfy the requirement krbV.

**Comment by tkdchen** [comment]
@fbacchella Sorry, no progress so far. Currently, I don't have enough time to continue working on this issue and finish it in a short term.

**Comment by tkdchen** [comment]
This is done. Please check latest version of ``0.6`` from PyPI[1].

@fbacchella FYI.

[1] https://pypi.python.org/pypi/krbcontext
