### ISSUE TITLE
Don't support alternate ccache type

### ISSUE THREAD

**Issue by fbacchella** [tkdchen/python-krbcontext#23]
With recent version version of kerberos, ccache_file can be something else than a file, for example:

    KRB5CCNAME=MEMORY:mem kinit

But with python-krbcontext:

import krbcontext

ENV_KRB5CCNAME = 'KRB5CCNAME'
with krbcontext.krbcontext(principal='host/...', ccache_file='MEMORY:mem',using_keytab=True,keytab_file='/etc/krb5.keytab'):
        print os.environ[ENV_KRB5CCNAME]
        subprocess.call(["klist"])

return:

    mem

And of course, klist fails:

klist: No credentials cache found (filename: mem)

**Comment by tkdchen** [comment]
This is a problem indeed, because IIRC krbV does not support new credential cache collection. As you see, migration to python-gssapi should fix this.

**Comment by tkdchen** [comment]
Please try latest version of krbcontext from PyPI.
